<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <AssemblyName>Shackles.Wesp.Tests</AssemblyName>
    <RootNamespace>Shackles.Wesp.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="MSTest.TestAdapter" Version="4.1.0" />
    <PackageReference Include="MSTest.TestFramework" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Shackles.Wesp\Shackles.Wesp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\src\Shackles.App\espclient.dll"
          Link="espclient.dll"
          CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
